import assert from "node:assert/strict";
import {webcrypto} from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import {DatabaseSync} from "node:sqlite";
import {fileURLToPath} from "node:url";
import {onRequest} from "../functions/api/[[path]].js";

if(!globalThis.crypto)globalThis.crypto=webcrypto;
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
class Statement{constructor(database,sql){this.database=database;this.sql=sql;this.args=[]}bind(...args){this.args=args;return this}async first(){return this.database.prepare(this.sql).get(...this.args)||null}async all(){return {results:this.database.prepare(this.sql).all(...this.args)}}async run(){const result=this.database.prepare(this.sql).run(...this.args);return {success:true,meta:{changes:Number(result.changes||0)}}}}
class D1{constructor(database){this.database=database}prepare(sql){return new Statement(this.database,sql)}async batch(rows){return Promise.all(rows.map(row=>row.run()))}}
const digest=async value=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(byte=>byte.toString(16).padStart(2,"0")).join("");
const users=[1,2,3,4].map(index=>({id:`0000000${index}-0000-4000-8000-00000000000${index}`,token:`token-${index}-`.padEnd(40,String(index)),nickname:`玩家${index}`}));
async function call(DB,user,path,method="GET",body){const request=new Request(`https://preview.test/api/online/key-battle/${path}`,{method,headers:{"content-type":"application/json","x-bl-client-id":user.id,"x-bl-client-token":user.token},body:body===undefined?undefined:JSON.stringify(body)});const response=await onRequest({request,env:{DB},params:{path:["online","key-battle",...path.split("/")]}});return {status:response.status,body:await response.json()}}
async function setup(){const database=new DatabaseSync(":memory:");database.exec("PRAGMA foreign_keys=ON");for(const name of ["0001_basketballlife_d1.sql","0002_leaderboard_read_optimization.sql","0003_v81_leaderboard_era.sql","0004_v9_leaderboard_era.sql","0005_online_key_battle.sql","0008_online_shared_world.sql"])database.exec(fs.readFileSync(path.join(root,"migrations",name),"utf8"));for(const user of users)database.prepare("INSERT INTO profiles(user_id,token_hash,nickname) VALUES(?,?,?)").run(user.id,await digest(user.token),user.nickname);return {database,DB:new D1(database)}}
async function createWorld(DB,three=false){const created=await call(DB,users[0],"rooms","POST",{role:"guard"}),code=created.body.room.code;await call(DB,users[1],`rooms/${code}/join`,"POST",{role:"wing"});if(three)await call(DB,users[2],`rooms/${code}/join`,"POST",{role:"big"});const started=await call(DB,users[0],`rooms/${code}/start`,"POST",{});return {code,started}}
async function advanceCheckpoint(DB,code,count=2,picks=[]){let state;for(let index=0;index<count;index++){const current=await call(DB,users[index],`rooms/${code}`),options=current.body.event.options,choice=picks[index]||options[Math.min(index,options.length-1)].id;state=await call(DB,users[index],`rooms/${code}/choices`,"POST",{choice});assert.equal(state.status,200)}return state}
async function advanceSeason(DB,code,count=2){let state;for(let chapter=0;chapter<6;chapter++)state=await advanceCheckpoint(DB,code,count);return state}

test("two players can start independent HBL careers in one world while one player cannot",async()=>{const {database,DB}=await setup(),created=await call(DB,users[0],"rooms","POST",{role:"guard"}),code=created.body.room.code;let state=await call(DB,users[0],`rooms/${code}/start`,"POST",{});assert.equal(state.status,409);await call(DB,users[1],`rooms/${code}/join`,"POST",{role:"wing"});state=await call(DB,users[0],`rooms/${code}/start`,"POST",{});assert.equal(state.status,200);assert.equal(state.body.world.chapter,1);assert.equal(state.body.careers.length,2);assert.ok(state.body.careers.every(row=>row.origin_route==="hbl"&&row.league==="HBL"));assert.notEqual(state.body.careers[0].team_name,state.body.careers[1].team_name);database.close()});

test("shared world exposes the same six-stage season rhythm as a complete solo career",async()=>{const {database,DB}=await setup(),{code,started}=await createWorld(DB);assert.deepEqual(started.body.world.flow,["季前訓練","一般事件","特殊事件","健康管理","球季結算","能力與生涯抉擇"]);assert.match(started.body.event.title,/第 1 季準備開始/);assert.equal(started.body.event.scope,"personal");const wing=await call(DB,users[1],`rooms/${code}`);assert.notEqual(started.body.event.title,wing.body.event.title);assert.equal(wing.body.world.year,started.body.world.year);database.close()});

test("a checkpoint waits for every human and applies different choices to independent careers",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);let state=await call(DB,users[0],`rooms/${code}/choices`,"POST",{choice:"train_skill"});assert.equal(state.body.world.chapter,1);assert.equal(state.body.submitted,true);state=await call(DB,users[1],`rooms/${code}/choices`,"POST",{choice:"train_recover"});assert.equal(state.body.world.chapter,2);const guard=state.body.careers.find(row=>row.position==="guard"),wing=state.body.careers.find(row=>row.position==="wing");assert.ok(guard.overall>wing.overall);assert.ok(wing.health>guard.health);database.close()});

test("one full cycle advances exactly one year and does not skip HBL",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);const state=await advanceSeason(DB,code);assert.equal(state.body.world.cycle,2);assert.equal(state.body.world.year,2027);assert.equal(state.body.world.chapter,1);assert.ok(state.body.careers.every(row=>row.age===17&&row.league==="HBL"));database.close()});

test("graduation opens independent college routes after three played HBL seasons",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await advanceSeason(DB,code);await advanceSeason(DB,code);for(let chapter=1;chapter<6;chapter++)await advanceCheckpoint(DB,code);let guard=await call(DB,users[0],`rooms/${code}`),wing=await call(DB,users[1],`rooms/${code}`);assert.equal(guard.body.world.chapter,6);assert.equal(guard.body.event.id,"hbl_graduation");const g=guard.body.event.options[0].id,w=wing.body.event.options.at(-1).id;const state=await advanceCheckpoint(DB,code,2,[g,w]);assert.equal(state.body.world.year,2029);assert.ok(state.body.careers.every(row=>row.age===19&&row.league!=="HBL"));if(g!==w)assert.notEqual(state.body.careers[0].league,state.body.careers[1].league);database.close()});

test("every third season inserts one logical shared intersection instead of repeating every round",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await advanceCheckpoint(DB,code);await advanceCheckpoint(DB,code);let state=await call(DB,users[0],`rooms/${code}`);assert.equal(state.body.event.scope,"personal");for(let chapter=3;chapter<=6;chapter++)await advanceCheckpoint(DB,code);await advanceCheckpoint(DB,code);await advanceCheckpoint(DB,code);state=await call(DB,users[0],`rooms/${code}`);assert.equal(state.body.event.scope,"personal");for(let chapter=3;chapter<=6;chapter++)await advanceCheckpoint(DB,code);await advanceCheckpoint(DB,code);await advanceCheckpoint(DB,code);state=await call(DB,users[0],`rooms/${code}`);assert.equal(state.body.world.cycle,3);assert.equal(state.body.world.chapter,3);assert.equal(state.body.event.scope,"intersection");database.close()});

test("three-player worlds wait for all three independent careers",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB,true);await call(DB,users[0],`rooms/${code}/choices`,"POST",{choice:"train_skill"});await call(DB,users[1],`rooms/${code}/choices`,"POST",{choice:"train_team"});let state=await call(DB,users[0],`rooms/${code}`);assert.equal(state.body.world.chapter,1);state=await call(DB,users[2],`rooms/${code}/choices`,"POST",{choice:"train_recover"});assert.equal(state.body.world.chapter,2);assert.equal(state.body.careers.length,3);assert.ok(state.body.careers.every(row=>row.origin_route==="hbl"));assert.equal(new Set(state.body.careers.map(row=>row.team_name)).size,3);database.close()});
