import assert from "node:assert/strict";
import {webcrypto} from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import {DatabaseSync} from "node:sqlite";
import {fileURLToPath} from "node:url";
import {onRequest} from "../functions/api/[[path]].js";

if(!globalThis.crypto)globalThis.crypto=webcrypto;
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
class Statement{constructor(database,sql){this.database=database;this.sql=sql;this.args=[]}bind(...args){this.args=args;return this}async first(){return this.database.prepare(this.sql).get(...this.args)||null}async all(){return {results:this.database.prepare(this.sql).all(...this.args)}}async run(){const result=this.database.prepare(this.sql).run(...this.args);return {success:true,meta:{changes:Number(result.changes||0)}}}}
class D1{constructor(database){this.database=database}prepare(sql){return new Statement(this.database,sql)}async batch(rows){return Promise.all(rows.map(row=>row.run()))}}
const digest=async value=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(byte=>byte.toString(16).padStart(2,"0")).join("");
const users=[1,2,3,4].map(index=>({id:`0000000${index}-0000-4000-8000-00000000000${index}`,token:`token-${index}-`.padEnd(40,String(index)),nickname:`玩家${index}`}));
async function call(DB,user,path,method="GET",body){const request=new Request(`https://preview.test/api/online/key-battle/${path}`,{method,headers:{"content-type":"application/json","x-bl-client-id":user.id,"x-bl-client-token":user.token},body:body===undefined?undefined:JSON.stringify(body)});const response=await onRequest({request,env:{DB},params:{path:["online","key-battle",...path.split("/")]}});return {status:response.status,body:await response.json()}}
async function setup(){const database=new DatabaseSync(":memory:");database.exec("PRAGMA foreign_keys=ON");for(const name of ["0001_basketballlife_d1.sql","0002_leaderboard_read_optimization.sql","0003_v81_leaderboard_era.sql","0004_v9_leaderboard_era.sql","0005_online_key_battle.sql","0008_online_shared_world.sql"])database.exec(fs.readFileSync(path.join(root,"migrations",name),"utf8"));for(const user of users)database.prepare("INSERT INTO profiles(user_id,token_hash,nickname) VALUES(?,?,?)").run(user.id,await digest(user.token),user.nickname);return {database,DB:new D1(database)}}
async function createWorld(DB,three=false){const created=await call(DB,users[0],"rooms","POST",{role:"guard"}),code=created.body.room.code;await call(DB,users[1],`rooms/${code}/join`,"POST",{role:"wing"});if(three)await call(DB,users[2],`rooms/${code}/join`,"POST",{role:"big"});const started=await call(DB,users[0],`rooms/${code}/start`,"POST",{});return {code,started}}
async function choose(DB,code,choices,count=2){let state;for(let index=0;index<count;index++)state=await call(DB,users[index],`rooms/${code}/choices`,"POST",{choice:choices[index]});return state}

test("two players can start independent HBL careers in one world while one player cannot",async()=>{const {database,DB}=await setup(),created=await call(DB,users[0],"rooms","POST",{role:"guard"}),code=created.body.room.code;let state=await call(DB,users[0],`rooms/${code}/start`,"POST",{});assert.equal(state.status,409);await call(DB,users[1],`rooms/${code}/join`,"POST",{role:"wing"});state=await call(DB,users[0],`rooms/${code}/start`,"POST",{});assert.equal(state.status,200);assert.equal(state.body.world.chapter,1);assert.equal(state.body.careers.length,2);assert.ok(state.body.careers.every(row=>row.origin_route==="hbl"&&row.league==="HBL"));assert.notEqual(state.body.careers[0].team_name,state.body.careers[1].team_name);database.close()});

test("players at the same HBL checkpoint receive position-specific story events",async()=>{const {database,DB}=await setup(),{code,started}=await createWorld(DB);assert.match(started.body.event.title,/教練把球交給你/);const wing=await call(DB,users[1],`rooms/${code}`);assert.match(wing.body.event.title,/對手王牌/);assert.equal(started.body.event.scope,"personal");assert.equal(wing.body.world.year,started.body.world.year);database.close()});

test("a personal checkpoint waits for humans but applies different choices to different careers",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);let state=await call(DB,users[0],`rooms/${code}/choices`,"POST",{choice:"train"});assert.equal(state.body.world.chapter,1);assert.equal(state.body.submitted,true);state=await call(DB,users[1],`rooms/${code}/choices`,"POST",{choice:"balance"});assert.equal(state.body.world.chapter,2);const guard=state.body.careers.find(row=>row.position==="guard"),wing=state.body.careers.find(row=>row.position==="wing");assert.equal(guard.overall,57);assert.equal(guard.health,83);assert.equal(wing.overall,55);assert.equal(wing.health,98);database.close()});

test("different college routes intersect without forcing players onto one team",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await choose(DB,code,["team","train"]);let state=await choose(DB,code,["uba","ncaa_d2"]);assert.equal(state.body.world.chapter,3);assert.equal(state.body.world.year,2029);assert.equal(state.body.event.scope,"intersection");assert.match(state.body.event.title,/U20 國家培訓觀察營/);assert.ok(state.body.careers.every(row=>row.age===19));const teamsBefore=state.body.careers.map(row=>row.team_name);state=await choose(DB,code,["challenge","connect"]);assert.equal(state.body.world.chapter,4);assert.equal(state.body.world.year,2032);assert.ok(state.body.careers.every(row=>row.age===22));assert.deepEqual(state.body.careers.map(row=>row.team_name),teamsBefore);assert.ok(state.body.history.some(row=>row.event_id==="u20_camp"));database.close()});

test("college routes converge at a five-game summer league then produce independent contracts",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await choose(DB,code,["team","train"]);await choose(DB,code,["uba","ncaa_d2"]);await choose(DB,code,["challenge","connect"]);let state=await choose(DB,code,["domestic","development"]);assert.equal(state.body.world.chapter,5);assert.match(state.body.event.title,/五場夏季聯賽/);assert.notEqual(state.body.careers[0].league,state.body.careers[1].league);state=await choose(DB,code,["winning","showcase"]);assert.equal(state.body.world.chapter,6);state=await choose(DB,code,["accept","negotiate"]);assert.equal(state.body.world.cycle,2);assert.equal(state.body.world.year,2033);assert.equal(state.body.world.chapter,1);assert.ok(state.body.careers.every(row=>row.age===23));assert.notEqual(state.body.careers[0].team_name,state.body.careers[1].team_name);assert.ok(state.body.careers.every(row=>row.contract_years>=1));database.close()});

test("professional cycles never send players back to HBL graduation or college selection",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await choose(DB,code,["team","train"]);await choose(DB,code,["uba","ncaa_d2"]);await choose(DB,code,["challenge","connect"]);await choose(DB,code,["domestic","development"]);await choose(DB,code,["winning","showcase"]);let state=await choose(DB,code,["accept","negotiate"]);await choose(DB,code,["team","balance"]);state=await call(DB,users[0],`rooms/${code}`);assert.equal(state.body.world.cycle,2);assert.equal(state.body.world.chapter,2);assert.match(state.body.event.title,/輪替定位改變/);assert.doesNotMatch(state.body.event.title,/HBL|高中|大學|學業/);assert.deepEqual(state.body.event.options.map(row=>row.id),["train","team","balance"]);assert.ok(state.body.event.options.every(row=>!/學業/.test(`${row.label}${row.detail}`)));database.close()});

test("three-player worlds wait for all three real HBL careers",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB,true);await call(DB,users[0],`rooms/${code}/choices`,"POST",{choice:"team"});await call(DB,users[1],`rooms/${code}/choices`,"POST",{choice:"train"});let state=await call(DB,users[0],`rooms/${code}`);assert.equal(state.body.world.chapter,1);state=await call(DB,users[2],`rooms/${code}/choices`,"POST",{choice:"balance"});assert.equal(state.body.world.chapter,2);assert.equal(state.body.careers.length,3);assert.ok(state.body.careers.every(row=>row.origin_route==="hbl"));assert.equal(new Set(state.body.careers.map(row=>row.team_name)).size,3);database.close()});
