import assert from "node:assert/strict";
import {webcrypto} from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import {DatabaseSync} from "node:sqlite";
import {fileURLToPath} from "node:url";
import {onRequest} from "../functions/api/[[path]].js";
import {advanceSharedStory,personalizeStoryEvent,sharedStoryEventFor,STORY_NODES} from "../functions/api/shared-career-stories.js";
import {midseasonEventFor,SHARED_SEASON_EVENTS} from "../functions/api/shared-season-events.js";

if(!globalThis.crypto)globalThis.crypto=webcrypto;
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const source=name=>fs.readFileSync(path.join(root,name),"utf8");
const frontend=source("js/online/key-battle.js"),server=source("functions/api/key-battle.js"),storage=source("js/storage.js"),career=source("js/ui/career-view.js"),season=source("js/career/season-engine.js"),retirement=source("js/ui/retirement-view.js"),board=source("js/leaderboard/leaderboard-api.js");
class Statement{constructor(database,sql){this.database=database;this.sql=sql;this.args=[]}bind(...args){this.args=args;return this}async first(){return this.database.prepare(this.sql).get(...this.args)||null}async all(){return {results:this.database.prepare(this.sql).all(...this.args)}}async run(){const result=this.database.prepare(this.sql).run(...this.args);return {success:true,meta:{changes:Number(result.changes||0)}}}}
class D1{constructor(database){this.database=database}prepare(sql){return new Statement(this.database,sql)}async batch(rows){return Promise.all(rows.map(row=>row.run()))}}
const digest=async value=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(byte=>byte.toString(16).padStart(2,"0")).join("");
const users=[1,2,3].map(index=>({id:`0000000${index}-0000-4000-8000-00000000000${index}`,token:`token-${index}-`.padEnd(40,String(index)),nickname:`玩家${index}`}));
async function call(DB,user,route,method="GET",body){const request=new Request(`https://preview.test/api/online/key-battle/${route}`,{method,headers:{"content-type":"application/json","x-bl-client-id":user.id,"x-bl-client-token":user.token},body:body===undefined?undefined:JSON.stringify(body)}),response=await onRequest({request,env:{DB},params:{path:["online","key-battle",...route.split("/")]}});return {status:response.status,body:await response.json()}}
async function setup(){const database=new DatabaseSync(":memory:");database.exec("PRAGMA foreign_keys=ON");for(const name of ["0001_basketballlife_d1.sql","0002_leaderboard_read_optimization.sql","0003_v81_leaderboard_era.sql","0004_v9_leaderboard_era.sql","0005_online_key_battle.sql","0008_online_shared_world.sql"])database.exec(source(`migrations/${name}`));for(const user of users)database.prepare("INSERT INTO profiles(user_id,token_hash,nickname) VALUES(?,?,?)").run(user.id,await digest(user.token),user.nickname);return {database,DB:new D1(database)}}
async function createWorld(DB,mode="complete"){const created=await call(DB,users[0],"rooms","POST",{role:"guard"}),code=created.body.room.code;await call(DB,users[1],`rooms/${code}/join`,"POST",{role:"wing"});return {code,started:await call(DB,users[0],`rooms/${code}/start`,"POST",{mode})}}
const snapshot=(ready,year=2026,extra={})=>({year,age:16,path:"HBL",team:"測試高中",overall:58,health:91,reputation:30,careerPower:6200,stage:"points",mode:"complete",ready,...extra});

test("cross-season multiplayer catalog contains ten authored lines with three nodes each",()=>{assert.deepEqual(Object.keys(STORY_NODES).sort(),["championship","contract","injury","national","overseas","partnership","recruiting","reunion","rivalry","succession"]);for(const nodes of Object.values(STORY_NODES)){assert.equal(nodes.length,3);for(const node of nodes){assert.ok(node.title.length>=8);assert.ok(node.detail.length>=35);assert.ok(node.options.length>=1)}}});

test("all thirty multiplayer story nodes are unique, resolved copy",()=>{const nodes=Object.values(STORY_NODES).flat(),titles=nodes.map(node=>node.title);assert.equal(nodes.length,30);assert.equal(new Set(titles).size,30);for(const node of nodes){assert.doesNotMatch(`${node.title}${node.detail}${node.options.map(option=>`${option.label}${option.detail}`).join("")}`,/\{\{|undefined|null|待補|TODO/i)}});

test("midseason multiplayer expands to twelve contextual events without changing the shared-round contract",()=>{assert.equal(Object.keys(SHARED_SEASON_EVENTS).length,12);for(const event of Object.values(SHARED_SEASON_EVENTS)){assert.ok(event.title.length>=6);assert.ok(event.detail.length>=35);if(event.options){assert.equal(event.options.length,3);assert.deepEqual(event.options.map(option=>option.id),event.kind==="competitive"?["shared_attack","shared_contain","shared_adjust"]:["shared_create","shared_finish","shared_anchor"])}}const hbl=[{user_id:"a",player_name:"甲",league:"HBL",team_name:"南弧高中",age:17,health:90,position:"guard",career_flags:"{}"},{user_id:"b",player_name:"乙",league:"HBL",team_name:"鈦山高中",age:17,health:90,position:"wing",career_flags:"{}"}];assert.equal(midseasonEventFor(hbl,2027).type,"hbl_elimination");const veterans=hbl.map((row,index)=>({...row,league:"台灣職籃",team_name:"港灣聯隊",age:index?26:36,contract_years:2}));assert.equal(midseasonEventFor(veterans,2041).type,"veteran_handoff")});

test("a young NBA professional is not misclassified as a college player",()=>{const proRows=[{user_id:"a",player_name:"新秀甲",league:"NBA",team_name:"東岸隊",age:20,health:90,contract_years:0,career_flags:JSON.stringify({nationalEligible:false})},{user_id:"b",player_name:"新秀乙",league:"NBA",team_name:"西岸隊",age:20,health:90,contract_years:0,career_flags:JSON.stringify({nationalEligible:false})}],collegeRows=proRows.map((row,index)=>({...row,league:"UBA",team_name:index?"建行科大":"政治大學"}));assert.equal(sharedStoryEventFor(proRows,2031).storyLine,"contract");assert.equal(sharedStoryEventFor(collegeRows,2031),null)});

test("a hostile rivalry returns with player names, prior choices, and a repair option",()=>{const rows=[{user_id:"a",player_name:"阿凱",league:"HBL",team_name:"南山高中",age:16,health:90,career_flags:"{}"},{user_id:"b",player_name:"小峰",league:"HBL",team_name:"能仁家商",age:16,health:90,career_flags:"{}"}];const first=sharedStoryEventFor(rows,2026),state=advanceSharedStory(rows,first,[{user_id:"a",choice:"rival_attack"},{user_id:"b",choice:"rival_attack"}],2026);for(const row of rows){row.age=17;row.career_flags=JSON.stringify({sharedStory:state})}const second=sharedStoryEventFor(rows,2027);assert.equal(second.storyNode,2);assert.match(second.detail,/阿凱選擇/);assert.match(second.detail,/小峰選擇/);assert.match(second.detail,/關係緊張/);assert.ok(second.options.some(option=>option.id==="story_repair"))});

test("injury and succession openings ask different questions according to the human role",()=>{const injuryRows=[{user_id:"hurt",player_name:"傷者",league:"台灣職籃",team_name:"港灣聯隊",age:27,health:45,position:"guard",career_flags:JSON.stringify({injured:true})},{user_id:"fit",player_name:"隊友",league:"台灣職籃",team_name:"港灣聯隊",age:29,health:92,position:"wing",career_flags:"{}"}],injury=sharedStoryEventFor(injuryRows,2037);assert.ok(personalizeStoryEvent(injury,injuryRows,"hurt").options.some(option=>option.id==="accept_help"));assert.ok(personalizeStoryEvent(injury,injuryRows,"fit").options.some(option=>option.id==="carry"));const veteranRows=[{user_id:"old",player_name:"老將",league:"台灣職籃",team_name:"北城飛隼",age:36,health:90,position:"guard",career_flags:"{}"},{user_id:"young",player_name:"新核",league:"台灣職籃",team_name:"北城飛隼",age:26,health:90,position:"wing",career_flags:"{}"}],succession=sharedStoryEventFor(veteranRows,2042);assert.equal(succession.storyLine,"succession");assert.ok(personalizeStoryEvent(succession,veteranRows,"old").options.some(option=>option.id==="mentor"));assert.ok(personalizeStoryEvent(succession,veteranRows,"young").options.some(option=>option.id==="learn"))});

test("shared career launches the real solo engine and only adds a season-boundary intersection",()=>{assert.match(frontend,/startCareer\(context\)/);assert.match(frontend,/resumeShared\(context\.code\)/);assert.match(frontend,/intersectionScreen/);assert.doesNotMatch(frontend,/renderEvent/);assert.match(season,/BasketballLifeKeyBattle\?\.finishSeason/);assert.match(career,/function startCareer\(sharedContext=null\)/)});

test("each player keeps the complete solo character setup",()=>{for(const field of ["pos","height","wingspan","birthplace","handedness","jerseyNumber","seed","mode"])assert.match(frontend,new RegExp(`${field}:`));assert.match(frontend,/setupSeedValue\(\)/);assert.match(career,/sharedContext\?\.handedness/)});

test("shared saves are isolated from the normal single-player save",()=>{assert.match(storage,/\.shared\.\$\{String\(code/);assert.match(storage,/activeCareerSaveKey/);assert.match(storage,/if\(saveKey===CAREER_SAVE_KEY\)updateContinueCareerPanel/)});

test("room owner chooses complete or highlight and the server returns the solo engine contract",async()=>{const {database,DB}=await setup(),{started}=await createWorld(DB,"highlight");assert.equal(started.status,200);assert.equal(started.body.world.engine,"solo-v9");assert.equal(started.body.world.mode,"highlight");assert.match(started.body.world.seed,/^[A-Z2-9]{6}SW$/);assert.equal(started.body.careers.length,2);database.close()});

test("the original career flow pauses at a real midseason checkpoint",()=>{assert.match(frontend,/function maybeMidseasonCheckpoint\(/);assert.match(frontend,/checkpoint-choice/);assert.match(frontend,/確認共同結果，繼續本季/);assert.match(source("js/ui/event-view.js"),/BasketballLifeKeyBattle\?\.maybeMidseasonCheckpoint/);assert.doesNotMatch(frontend,/renderMidseasonPage|onlineBattlePage.*midseason/)});

test("two players meet during the same season and one counter-choice creates one authoritative result",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);let state=await call(DB,users[0],`rooms/${code}/checkpoint`,"POST",snapshot(false));assert.equal(state.body.advance,false);assert.equal(state.body.players.filter(row=>row.ready).length,1);state=await call(DB,users[1],`rooms/${code}/checkpoint`,"POST",snapshot(false));assert.equal(state.body.intersection.type,"hbl_match");assert.equal(state.body.intersection.checkpoint,"midseason");let choice=await call(DB,users[0],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_attack"});assert.equal(choice.body.advance,false);choice=await call(DB,users[1],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_contain"});assert.equal(choice.body.advance,true);assert.equal(choice.body.result.commonOutcome,"success");assert.equal(database.prepare("SELECT timeline_year FROM online_shared_worlds WHERE room_code=?").get(code).timeline_year,2026);assert.equal(database.prepare("SELECT COUNT(*) count FROM online_shared_history WHERE room_code=? AND chapter_number=45").get(code).count,2);const flags=database.prepare("SELECT career_flags FROM online_shared_player_careers WHERE room_code=?").all(code).map(row=>JSON.parse(row.career_flags));assert.ok(flags.every(row=>row.midseasonResolvedYear===2026));state=await call(DB,users[1],`rooms/${code}/checkpoint`,"POST",snapshot(false));assert.equal(state.body.advance,true);assert.equal(state.body.result.eventId,choice.body.result.eventId);database.close()});

test("same-team midseason play fails on duplicate jobs and succeeds on complementary jobs",async()=>{const run=async(second)=>{const {database,DB}=await setup(),{code}=await createWorld(DB);database.prepare("UPDATE online_shared_player_careers SET league='台灣職籃',team_name='港灣聯隊',age=25,contract_years=2 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/checkpoint`,"POST",snapshot(false,2026,{age:25,path:"台灣職籃",team:"港灣聯隊"}));const ready=await call(DB,users[1],`rooms/${code}/checkpoint`,"POST",snapshot(false,2026,{age:25,path:"台灣職籃",team:"港灣聯隊"}));assert.equal(ready.body.intersection.type,"same_team_possession");await call(DB,users[0],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_create"});const result=await call(DB,users[1],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:second});database.close();return result.body.result};const duplicate=await run("shared_create"),complement=await run("shared_finish");assert.equal(duplicate.commonOutcome,"failure");assert.equal(complement.commonOutcome,"success");assert.ok(complement.shared.cooperationDelta>duplicate.shared.cooperationDelta)});

test("three-player cooperation requires all three basketball jobs and saves one result per human",async()=>{const {database,DB}=await setup(),created=await call(DB,users[0],"rooms","POST",{role:"guard"}),code=created.body.room.code;await call(DB,users[1],`rooms/${code}/join`,"POST",{role:"wing"});await call(DB,users[2],`rooms/${code}/join`,"POST",{role:"big"});await call(DB,users[0],`rooms/${code}/start`,"POST",{mode:"complete"});database.prepare("UPDATE online_shared_player_careers SET league='台灣職籃',team_name='港灣聯隊',age=25,contract_years=2 WHERE room_code=?").run(code);for(const user of users)await call(DB,user,`rooms/${code}/checkpoint`,"POST",snapshot(false,2026,{age:25,path:"台灣職籃",team:"港灣聯隊"}));await call(DB,users[0],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_create"});await call(DB,users[1],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_finish"});const result=await call(DB,users[2],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_anchor"});assert.equal(result.body.result.commonOutcome,"success");assert.equal(result.body.result.shared.standings.length,3);assert.equal(database.prepare("SELECT COUNT(*) count FROM online_shared_history WHERE room_code=? AND chapter_number=45").get(code).count,3);const recovered=await call(DB,users[0],`rooms/${code}/checkpoint`,"POST",snapshot(false,2026,{age:25,path:"台灣職籃",team:"港灣聯隊"}));assert.equal(recovered.body.advance,true);assert.equal(recovered.body.result.eventId,result.body.result.eventId);database.close()});

test("a retired teammate cannot trap the remaining player at the midseason checkpoint",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await call(DB,users[1],`rooms/${code}/retire`,"POST",{year:2026});const state=await call(DB,users[0],`rooms/${code}/checkpoint`,"POST",snapshot(false));assert.equal(state.body.advance,true);assert.equal(state.body.skip,true);assert.equal(state.body.result,undefined);database.close()});

test("season boundary waits for every human and opens the first cross-season rivalry node",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);let state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));assert.equal(state.status,200);assert.equal(state.body.advance,false);assert.equal(state.body.players.filter(row=>row.ready).length,1);state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true));assert.equal(state.body.advance,false);assert.ok(state.body.players.every(row=>row.ready));assert.equal(state.body.intersection.type,"story_rivalry");assert.equal(state.body.intersection.storyNode,1);assert.match(state.body.intersection.title,/測試高中.*真人名字/);assert.match(state.body.intersection.detail,/真人是/);database.close()});

test("both rivalry choices create a shared result, shared state, and one world advance",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true));let state=await call(DB,users[0],`rooms/${code}/intersection`,"POST",{year:2026,choice:"rival_attack"});assert.equal(state.body.advance,false);assert.equal(state.body.submitted,true);state=await call(DB,users[1],`rooms/${code}/intersection`,"POST",{year:2026,choice:"rival_respect"});assert.equal(state.body.advance,true);assert.equal(state.body.result.eventType,"story_rivalry");assert.equal(state.body.result.storyNode,1);assert.equal(state.body.result.shared.standings.length,2);const stored=database.prepare("SELECT career_flags FROM online_shared_player_careers WHERE room_code=?").all(code).map(row=>JSON.parse(row.career_flags).sharedStory);assert.equal(stored.length,2);assert.ok(stored.every(item=>item.lines.rivalry.node===1));state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));assert.equal(state.body.advance,true);assert.equal(database.prepare("SELECT timeline_year FROM online_shared_worlds WHERE room_code=?").get(code).timeline_year,2027);database.close()});

test("sync rejects a profile that has no career row instead of waiting forever",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);const state=await call(DB,users[2],`rooms/${code}/sync`,"POST",snapshot(true));assert.equal(state.status,409);assert.match(state.body.error,/找不到你/);database.close()});

test("a non-member cannot submit an intersection choice",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true));const state=await call(DB,users[2],`rooms/${code}/intersection`,"POST",{year:2026,choice:"duel"});assert.equal(state.status,403);database.close()});

test("routine years advance without forcing another shared choice",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);database.prepare("UPDATE online_shared_worlds SET timeline_year=2027,cycle_number=2 WHERE room_code=?").run(code);let state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2027,{age:17}));assert.equal(state.body.advance,false);state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2027,{age:17}));assert.equal(state.body.advance,true);assert.equal(state.body.intersection,undefined);database.close()});

test("professional playoffs and finals require real solo-career results",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB),pro=(team,extra={})=>snapshot(true,2032,{age:24,path:"台灣職籃",team,nationalEligible:false,...extra}),completeLines=Object.fromEntries(Object.keys(STORY_NODES).map(line=>[line,{node:3,status:"complete",lastYear:2031}]));database.prepare("UPDATE online_shared_player_careers SET contract_years=2,career_flags=? WHERE room_code=?").run(JSON.stringify({sharedStory:{version:1,lines:completeLines,history:[]}}),code);database.prepare("UPDATE online_shared_worlds SET timeline_year=2032,cycle_number=7 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",pro("北城飛隼"));let state=await call(DB,users[1],`rooms/${code}/sync`,"POST",pro("南岸浪潮"));assert.equal(state.body.intersection.type,"pro_regular");assert.notEqual(state.body.intersection.type,"pro_finals");database.prepare("UPDATE online_shared_worlds SET timeline_year=2033,cycle_number=8 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2033,{age:25,path:"台灣職籃",team:"北城飛隼",nationalEligible:false,madePlayoffs:true,playoffFinish:"四強"}));state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2033,{age:25,path:"台灣職籃",team:"南岸浪潮",nationalEligible:false,madePlayoffs:true,playoffFinish:"八強"}));assert.equal(state.body.intersection.type,"pro_playoffs");database.prepare("UPDATE online_shared_worlds SET timeline_year=2034,cycle_number=9 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2034,{age:26,path:"台灣職籃",team:"北城飛隼",nationalEligible:false,madePlayoffs:true,playoffFinish:"冠軍"}));state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2034,{age:26,path:"台灣職籃",team:"南岸浪潮",nationalEligible:false,madePlayoffs:true,playoffFinish:"亞軍"}));assert.equal(state.body.intersection.type,"pro_finals");database.close()});

test("injury story only appears for actual teammates and gives injured and healthy players different text",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB),base={age:24,path:"台灣職籃",team:"港灣聯隊"};database.prepare("UPDATE online_shared_worlds SET timeline_year=2032,cycle_number=7 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2032,{...base,health:48,injured:true}));let state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2032,{...base,health:92,injured:false}));assert.equal(state.body.intersection.type,"story_injury");assert.ok(state.body.intersection.options.some(option=>option.id==="carry"));state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2032,{...base,health:48,injured:true}));assert.ok(state.body.intersection.options.some(option=>option.id==="accept_help"));assert.ok(state.body.intersection.options.some(option=>option.id==="protect_role"));assert.ok(!state.body.intersection.options.some(option=>option.id==="compete_slot"));database.close()});

test("same-team partnership gives each position its own basketball responsibility",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB),base={age:24,path:"台灣職籃",team:"港灣聯隊",health:90};database.prepare("UPDATE online_shared_worlds SET timeline_year=2032,cycle_number=7 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2032,base));let state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2032,base));assert.equal(state.body.intersection.type,"story_partnership");assert.equal(state.body.intersection.options.find(option=>option.id==="create").label,"二次組織");state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2032,base));assert.equal(state.body.intersection.options.find(option=>option.id==="create").label,"持球發動");database.close()});

test("same-team players need complementary choices instead of receiving free cooperation",async()=>{const run=async(secondChoice)=>{const {database,DB}=await setup(),{code}=await createWorld(DB),base={age:24,path:"台灣職籃",team:"港灣聯隊",health:90};database.prepare("UPDATE online_shared_worlds SET timeline_year=2032,cycle_number=7 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2032,base));await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2032,base));await call(DB,users[0],`rooms/${code}/intersection`,"POST",{year:2032,choice:"create"});const result=await call(DB,users[1],`rooms/${code}/intersection`,"POST",{year:2032,choice:secondChoice});database.close();return result.body.result.shared};const overlap=await run("create"),complement=await run("finish");assert.match(overlap.title,/責任重疊/);assert.match(complement.title,/互補/);assert.ok(complement.cooperationDelta>overlap.cooperationDelta)});

test("national camp respects eligibility and cross-team injuries do not become teammate support",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);database.prepare("UPDATE online_shared_worlds SET timeline_year=2031,cycle_number=6 WHERE room_code=?").run(code);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2031,{age:21,path:"UBA",team:"政治大學",nationalEligible:false,health:45,injured:true}));const state=await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2031,{age:21,path:"UBA",team:"建行科大",nationalEligible:true,health:90}));assert.equal(state.body.advance,true);assert.equal(state.body.intersection,undefined);database.close()});

test("shared career can be retried or removed locally without touching the solo save",()=>{assert.match(frontend,/retrySeasonSync/);assert.match(frontend,/leaveSharedCareer/);assert.match(storage,/clearShared/)});

test("opening multiplayer separates new-world setup from shared save slots",()=>{assert.match(frontend,/建立新世界時使用/);assert.match(frontend,/共享生涯存檔/);assert.match(frontend,/本機進度已保存/);assert.match(frontend,/async function open\(\).*await loadRooms\(\);renderLobby\(\)/s);assert.doesNotMatch(frontend,/async function open\(\).*rooms\/\$\{remembered\}/s)});

test("shared save slots can return, cancel locally, hide, and rejoin by code",()=>{for(const name of ["backToSaveList","cancelSharedSave","hiddenRooms","setRoomHidden"])assert.match(frontend,new RegExp(name));assert.match(frontend,/取消這份生涯/);assert.match(frontend,/setRoomHidden\(code,false\)/)});

test("shared careers provide contextual intersections instead of one generic event",()=>{const catalog=server.slice(server.indexOf("const INTERSECTIONS="),server.indexOf("const CHOICE_EFFECTS="));for(const type of ["hbl_match","recruiting_race","college_invite","national_camp","pro_regular","pro_playoffs","pro_finals","same_team_coop","market_reunion","trade_window","injury_support","veteran_handoff","cross_league","teammate_retirement"])assert.match(catalog,new RegExp(`${type}:`));assert.doesNotMatch(catalog,/id:"duel"|id:"team"|id:"connect"/)});

test("a shared result is confirmed on the existing career screen and carries risk past season reset",()=>{assert.match(frontend,/function resultScreen\(/);assert.match(frontend,/確認結果，進入下一季/);assert.match(frontend,/pendingResult/);assert.match(frontend,/function applyNextSeasonIntersection\(/);assert.match(frontend,/finish\(\);applyNextSeasonIntersection\(result,year\)/);assert.match(frontend,/外界評價/);assert.doesNotMatch(frontend,/球隊信任 \$\{fx\.rep/)});

test("multiplayer history extends the existing retirement and leaderboard pages",()=>{assert.match(retirement,/function retirementSharedWorldHTML\(/);assert.match(retirement,/共同生涯/);assert.match(board,/多人合作排行榜/);assert.match(board,/online\/key-battle\/rankings/)});

test("cooperation ranking requires a complete shared season and combines average BL POWER with shared results",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await call(DB,users[0],`rooms/${code}/checkpoint`,"POST",snapshot(false));await call(DB,users[1],`rooms/${code}/checkpoint`,"POST",snapshot(false));await call(DB,users[0],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_attack"});await call(DB,users[1],`rooms/${code}/checkpoint-choice`,"POST",{year:2026,choice:"shared_contain"});let ranking=await call(DB,users[0],"rankings");assert.equal(ranking.body.rows.length,0);await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));await call(DB,users[1],`rooms/${code}/sync`,"POST",snapshot(true,2026,{careerPower:10000}));await call(DB,users[0],`rooms/${code}/intersection`,"POST",{year:2026,choice:"rival_adapt"});await call(DB,users[1],`rooms/${code}/intersection`,"POST",{year:2026,choice:"rival_respect"});ranking=await call(DB,users[0],"rankings");assert.equal(ranking.status,200);assert.equal(ranking.body.rows.length,1);const row=ranking.body.rows[0];assert.equal(row.events,2);assert.equal(row.midseasonEvents,1);assert.equal(row.storyChapters,1);assert.equal(row.rivalryEvents,2);assert.equal(row.players,2);assert.equal(row.averageCareerPower,8100);assert.equal(row.score,Object.values(row.scoreBreakdown).reduce((sum,value)=>sum+value,0));assert.equal(row.rankStage,"剛起步");assert.match(row.room,/^[A-Z2-9]{2}••••$/);database.close()});

test("a retired player creates one farewell event and no longer blocks active teammates",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);const retired=await call(DB,users[1],`rooms/${code}/retire`,"POST",{year:2026});assert.equal(retired.body.retired,true);let state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));assert.equal(state.body.advance,false);assert.equal(state.body.intersection.type,"teammate_retirement");assert.match(state.body.intersection.title,/玩家2.*退休/);state=await call(DB,users[0],`rooms/${code}/intersection`,"POST",{year:2026,choice:"honor"});assert.equal(state.body.advance,true);assert.equal(state.body.result.eventType,"teammate_retirement");state=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true,2027));assert.equal(state.body.advance,true);assert.equal(state.body.intersection,undefined);assert.match(retirement,/notifyRetirement/);assert.match(retirement,/retirementSharedWorldHTML/);database.close()});

test("room owners can reversibly archive worlds and archived worlds stop consuming the active-room limit",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);let denied=await call(DB,users[1],`rooms/${code}/archive`,"POST",{});assert.equal(denied.status,403);let archived=await call(DB,users[0],`rooms/${code}/archive`,"POST",{});assert.equal(archived.body.archived,true);assert.equal(database.prepare("SELECT status FROM online_key_battle_rooms WHERE room_code=?").get(code).status,"finished");const blocked=await call(DB,users[0],`rooms/${code}/sync`,"POST",snapshot(true));assert.equal(blocked.status,409);const created=await call(DB,users[0],"rooms","POST",{role:"guard"});assert.equal(created.status,200);const restored=await call(DB,users[0],`rooms/${code}/restore`,"POST",{});assert.equal(restored.body.room.status,"playing");database.close()});

test("all retired players produce one shared-world epilogue without inventing another season",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await call(DB,users[1],`rooms/${code}/retire`,"POST",{year:2048});const final=await call(DB,users[0],`rooms/${code}/retire`,"POST",{year:2050});assert.equal(final.status,200);assert.equal(final.body.epilogue.players.length,2);assert.equal(final.body.epilogue.years,"2026–2050");assert.match(final.body.epilogue.detail,/玩家1、玩家2/);const room=await call(DB,users[0],`rooms/${code}`);assert.equal(room.body.room.completed,true);assert.equal(room.body.room.status,"finished");assert.equal(room.body.epilogue.events,0);database.close()});

test("naturally completed shared worlds cannot be reopened",async()=>{const {database,DB}=await setup(),{code}=await createWorld(DB);await call(DB,users[1],`rooms/${code}/retire`,"POST",{year:2048});await call(DB,users[0],`rooms/${code}/retire`,"POST",{year:2050});const restored=await call(DB,users[0],`rooms/${code}/restore`,"POST",{});assert.equal(restored.status,409);assert.match(restored.body.error,/自然完成/);database.close()});

test("shared saves expose portable backup and restore controls without replacing the career page",()=>{for(const token of ["exportSharedCareerSave","importSharedCareerSave","下載備份","匯入共享生涯備份","archiveWorld","restoreWorld","最後同步","共享世界共同終章"])assert.match(`${storage}\n${frontend}\n${retirement}`,new RegExp(token));assert.match(storage,/basketballlife-shared-career/);assert.doesNotMatch(frontend,/renderOnlineCareerPage|sharedCareerPage/)});
