(function(){
 const $=id=>document.getElementById(id),roles={guard:["後衛","控球／得分後場","PG"],wing:["側翼","攻守連接與對位","SF"],big:["內線","禁區終結與護框","C"]};
 const state={role:"guard",mode:"complete",room:null,rooms:[],poll:0,busy:false,error:"",finishing:false};
 const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
 const nickname=()=>window.BasketballLifeOnline?.nickname?.()||"";
 function currentSetup(){return {name:$("playerNameInput")?.value.trim()||nickname()||"共享世界球員",pos:chosenPos,height:chosenHeight,wingspan:chosenWingspan,birthplace:chosenBirthplace,handedness:$("handednessInput")?.value||"右手",jerseyNumber:Number($("jerseyNumberInput")?.value)||7,seed:setupSeedValue(),mode:state.mode}}
 function setupRole(pos){return ["PG","SG"].includes(pos)?"guard":pos==="SF"?"wing":"big"}
 function saveSetup(code){try{localStorage.setItem(`bl_shared_setup_${code}`,JSON.stringify(currentSetup()))}catch(_){}}
 function readSetup(code){try{return JSON.parse(localStorage.getItem(`bl_shared_setup_${code}`)||"null")}catch(_){return null}}
 function stop(){clearInterval(state.poll);state.poll=0}
 function showGame(){$("setup")?.classList.add("hidden");$("communityPage")?.classList.add("hidden");$("onlineBattlePage")?.classList.add("hidden");$("game")?.classList.remove("hidden")}
 function lobbyHeader(data=null){const mine=data?.my_career||{},role=roles[mine.position||state.role]||roles.guard;showGame();$("game").dataset.stage="online";$("pname").textContent=mine.player_name||nickname()||"共享世界球員";$("ppos").textContent=role[2];$("teamname").textContent=mine.team_name?`・${mine.team_name}`:"";$("age").textContent=mine.age??16;$("year").textContent=2026;$("ovr").textContent="—";$("path").textContent="HBL";$("flow").innerHTML="";$("next").classList.add("hidden")}
 function peers(data){return `<div class="kbOnlinePeers">${(data.careers||[]).map(row=>`<article class="kbCareerCard ${row.is_me?"mine":""}"><span>${row.is_me?"你的球員":roles[row.position]?.[0]||"隊友"}</span><b>${esc(row.player_name)}</b><small>${esc(row.team_name)}・${esc(row.league)}</small></article>`).join("")}</div>`}
 function renderLobby(){lobbyHeader();$("titleShelf").innerHTML='<span class="titleBadge">線上・2～3 人</span>';$("chapter").textContent="線上共享生涯";$("title").textContent="建立或加入共享世界";$("text").textContent="進房後直接遊玩原本的完整生涯或精華生涯；訓練、事件、比賽、健康、升學、合約與退休規則完全沿用單人模式。";const existing=state.rooms.length?`<div class="kbExistingWorlds"><div class="specialKicker">繼續既有世界</div>${state.rooms.map(room=>`<button onclick="BasketballLifeKeyBattle.resume('${esc(room.code)}')"><b>${esc(room.code)}・${esc(room.team_name)}</b><small>${room.year?`${room.year}・${room.player_count} 人`: `等待開局・${room.player_count} 人`}</small></button>`).join("")}</div>`:"";$("special").innerHTML=`${existing}<div class="specialStage career"><div class="specialKicker">你的場上位置</div><b>${roles[state.role][0]}</b><br><span class="mut">${roles[state.role][1]}</span></div>`;$("choices").innerHTML=`<div class="twoChoices">${Object.entries(roles).map(([id,[name,detail]])=>`<button class="choice ${state.role===id?"is-selected":""}" onclick="BasketballLifeKeyBattle.selectRole('${id}')"><b>${name}</b><small>${detail}</small></button>`).join("")}</div><div class="twoChoices"><button class="choice ${state.mode==="complete"?"is-selected":""}" onclick="BasketballLifeKeyBattle.selectMode('complete')"><b>完整生涯</b><small>與單人完整模式完全相同，逐季遊玩所有流程。</small></button><button class="choice ${state.mode==="highlight"?"is-selected":""}" onclick="BasketballLifeKeyBattle.selectMode('highlight')"><b>精華生涯</b><small>與單人精華模式完全相同，保留重大章節與轉折。</small></button></div><div class="kbInlineJoin"><input id="kbRoomInput" maxlength="6" autocomplete="off" placeholder="輸入 6 碼世界代碼"><button class="btn" onclick="BasketballLifeKeyBattle.join()">加入世界</button><button class="next" onclick="BasketballLifeKeyBattle.create()">建立新世界</button></div><div class="kbError">${esc(state.error)}</div>`}
 function renderWaiting(data){lobbyHeader(data);$("titleShelf").innerHTML=`<span class="titleBadge">世界｜${esc(data.room.code)}</span><button class="titleBadge kbShelfButton" onclick="BasketballLifeKeyBattle.copyCode()">複製代碼</button><button class="titleBadge kbShelfButton" onclick="BasketballLifeKeyBattle.switchRoom()">切換世界</button>`;$("chapter").textContent=`共享世界｜${data.room.code}`;$("title").textContent="等待隊友建立球員";$("text").textContent=data.players.length<2?"至少再一名真人玩家加入後才能開始。":"人數已足夠；房主選擇完整或精華節奏後，所有人直接進入同一套正式生涯引擎。";$("special").innerHTML=peers(data);$("choices").innerHTML=`${data.can_start?`<button class="choice kbStartChoice" onclick="BasketballLifeKeyBattle.start()"><b>開始${state.mode==="highlight"?"精華":"完整"}生涯</b><small>不是簡化事件版；直接從原本 HBL 生涯開局。</small></button>`:""}<div class="kbError">${esc(state.error)}</div>`}
 function sharedContext(data){const role=data.my_role||data.my_career?.position||state.role,setup=readSetup(data.room.code)||currentSetup();return {...setup,code:data.room.code,role,pos:setup.pos||roles[role]?.[2]||"PG",name:setup.name||data.my_career?.player_name||nickname()||"共享世界球員",mode:data.world.mode||setup.mode||"complete",seed:/^[A-Z0-9]{8}$/.test(setup.seed||"")?setup.seed:(data.world.seed||`${data.room.code}SW`)}}
 function launch(data){stop();state.room=data;const context=sharedContext(data);if(typeof p!=="undefined"&&p?.onlineSharedWorld?.code===context.code)return;if(window.BasketballLifeCareerSave?.readShared?.(context.code)){window.BasketballLifeCareerSave.resumeShared(context.code);return}startCareer(context)}
 function renderRoom(){if(!state.room)return renderLobby();if(state.room.world)return launch(state.room);renderWaiting(state.room)}
 async function request(path,options){if(state.busy)return null;state.busy=true;state.error="";try{return await window.BasketballLifeOnline.request(`online/key-battle/${path}`,options)}catch(error){state.error=error.message||"連線失敗";return null}finally{state.busy=false}}
 async function refresh(){if(!state.room)return;const data=await request(`rooms/${state.room.room.code}`);if(data){state.room=data;if(data.world)launch(data);else renderWaiting(data)}}
 function startPolling(){stop();state.poll=setInterval(refresh,1400)}
 async function loadRooms(){const data=await request("rooms");state.rooms=data?.rooms||[];return state.rooms}
 async function resume(code){const data=await request(`rooms/${code}`);if(data){state.room=data;remember(data.room.code);renderRoom();if(!data.world)startPolling()}else renderRoom()}
 async function open(){if(!nickname()){window.BasketballLifeOnline?.showNicknameModal?.();return}state.error="";let remembered="";try{remembered=localStorage.getItem("bl_key_battle_room")||""}catch(_){}if(remembered){const data=await request(`rooms/${remembered}`);if(data){state.room=data;renderRoom();if(!data.world)startPolling();return}}await loadRooms();renderRoom()}
 function close(){stop();$("game")?.classList.add("hidden");$("setup")?.classList.remove("hidden")}
 function selectRole(role){if(roles[role]){state.role=role;chosenPos=roles[role][2];if(typeof refreshSetupBody==="function")refreshSetupBody(true);renderLobby()}}
 function selectMode(mode){state.mode=mode==="highlight"?"highlight":"complete";chosenCareerMode=state.mode;state.room?renderWaiting(state.room):renderLobby()}
 function remember(code){try{localStorage.setItem("bl_key_battle_room",code)}catch(_){}}
 async function create(){const setup=currentSetup();if(!/^[A-Z0-9]{8}$/.test(setup.seed)){state.error="請先回首頁設定完整 8 碼 Seed";return renderLobby()}state.role=setupRole(setup.pos);const data=await request("rooms",{method:"POST",body:{role:state.role}});if(data){state.room=data;saveSetup(data.room.code);remember(data.room.code);renderRoom();startPolling()}else{await loadRooms();renderRoom()}}
 async function join(){const code=String($("kbRoomInput")?.value||"").trim().toUpperCase(),setup=currentSetup();if(!/^[A-Z2-9]{6}$/.test(code)){state.error="請輸入正確的 6 碼世界代碼";renderLobby();return}if(!/^[A-Z0-9]{8}$/.test(setup.seed)){state.error="請先回首頁設定完整 8 碼 Seed";return renderLobby()}state.role=setupRole(setup.pos);const data=await request(`rooms/${code}/join`,{method:"POST",body:{role:state.role}});if(data){state.room=data;saveSetup(data.room.code);remember(data.room.code);renderRoom();startPolling()}else renderLobby()}
 async function start(){if(!state.room)return;const data=await request(`rooms/${state.room.room.code}/start`,{method:"POST",body:{mode:state.mode}});if(data)launch(data);else renderWaiting(state.room)}
 async function copyCode(){const code=state.room?.room?.code;if(!code)return;try{await navigator.clipboard.writeText(code);state.error="共享世界代碼已複製"}catch(_){state.error=`共享世界代碼：${code}`}}
 async function switchRoom(){stop();state.room=null;state.error="";try{localStorage.removeItem("bl_key_battle_room")}catch(_){}await loadRooms();renderLobby()}
 function snapshot(ready=true){return {year:p.year,age:p.age,path:p.path,team:p.team,overall:typeof overall==="function"?overall():0,health:p.health,reputation:p.rep,stage:p.stage,mode:p.careerMode,retired:p.retired,ready}}
 function waitingScreen(players=[]){if(typeof window.render==="function")window.render();$("chapter").textContent=`共享世界・${p.year}`;$("title").textContent="本季完成，等待隊友";$("text").textContent="你的完整生涯進度已保存。所有真人玩家完成同一年球季後，才會一起進入下一季。";$("special").innerHTML=`<div class="kbOnlinePeers">${players.map(row=>`<article class="kbCareerCard"><b>${esc(row.player_name)}</b><small>${esc(row.team_name)}・OVR ${row.overall}</small><em>${row.ready?"本季已完成":"仍在遊玩本季"}</em></article>`).join("")}</div><div class="kbError">${esc(state.error)}</div>`;$("choices").innerHTML="";$("next").classList.add("hidden")}
 async function finishSeason(localFinish){if(state.finishing)return;state.finishing=true;const year=p.year,code=p.onlineSharedWorld.code;const check=async()=>{try{const data=await window.BasketballLifeOnline.request(`online/key-battle/rooms/${code}/sync`,{method:"POST",body:snapshot(true)});if(data.advance){state.finishing=false;p.onlineSharedWorld.readyYear=year;localFinish();saveCareerNow();return}waitingScreen(data.players);setTimeout(check,1400)}catch(error){state.error=error.message||"同步失敗，正在重試";waitingScreen([]);setTimeout(check,1800)}};await check()}
 window.BasketballLifeKeyBattle={open,close,selectRole,selectMode,create,join,start,copyCode,switchRoom,resume,finishSeason};
})();
