(function(){
 const $=id=>document.getElementById(id),roles={guard:["後衛","控球／得分後場","PG"],wing:["側翼","攻守連接與對位","SF"],big:["內線","禁區終結與護框","C"]};
 const state={role:"guard",mode:"complete",room:null,rooms:[],poll:0,busy:false,error:"",finishing:false,finishRun:0,localFinish:null,pendingAdvance:null,checkpointing:false,checkpointRun:0,checkpointResume:null};
 const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
 const nickname=()=>window.BasketballLifeOnline?.nickname?.()||"";
 function currentSetup(){return {name:$("playerNameInput")?.value.trim()||nickname()||"共享世界球員",pos:chosenPos,height:chosenHeight,wingspan:chosenWingspan,birthplace:chosenBirthplace,handedness:$("handednessInput")?.value||"右手",jerseyNumber:Number($("jerseyNumberInput")?.value)||7,seed:setupSeedValue(),mode:state.mode}}
 function setupRole(pos){return ["PG","SG"].includes(pos)?"guard":pos==="SF"?"wing":"big"}
 function saveSetup(code){try{localStorage.setItem(`bl_shared_setup_${code}`,JSON.stringify(currentSetup()))}catch(_){}}
 function readSetup(code){try{return JSON.parse(localStorage.getItem(`bl_shared_setup_${code}`)||"null")}catch(_){return null}}
 function hiddenRooms(){try{return new Set(JSON.parse(localStorage.getItem("bl_hidden_shared_rooms")||"[]"))}catch(_){return new Set()}}
 function setRoomHidden(code,hidden=true){const rooms=hiddenRooms();hidden?rooms.add(code):rooms.delete(code);try{localStorage.setItem("bl_hidden_shared_rooms",JSON.stringify([...rooms]))}catch(_){}}
 function stop(){clearInterval(state.poll);state.poll=0}
 function restoreScrollFocus(){document.body.tabIndex=-1;window.focus();document.body.focus({preventScroll:true})}
 function showGame(){$("setup")?.classList.add("hidden");$("communityPage")?.classList.add("hidden");$("onlineBattlePage")?.classList.add("hidden");$("game")?.classList.remove("hidden");setTimeout(restoreScrollFocus,0)}
 function lobbyHeader(data=null){const mine=data?.my_career||{},role=roles[mine.position||state.role]||roles.guard;showGame();$("game").dataset.stage="online";$("pname").textContent=mine.player_name||nickname()||"共享世界球員";$("ppos").textContent=role[2];$("teamname").textContent=mine.team_name?`・${mine.team_name}`:"";$("age").textContent=mine.age??16;$("year").textContent=2026;$("ovr").textContent="—";$("path").textContent="HBL";$("flow").innerHTML="";$("next").classList.add("hidden")}
 function peers(data){return `<div class="kbOnlinePeers">${(data.careers||[]).map(row=>`<article class="kbCareerCard ${row.is_me?"mine":""}"><span>${row.is_me?"你的球員":roles[row.position]?.[0]||"隊友"}</span><b>${esc(row.player_name)}</b><small>${esc(row.team_name)}・${esc(row.league)}</small></article>`).join("")}</div>`}
 function renderLobby(){lobbyHeader();$("titleShelf").innerHTML='<span class="titleBadge">線上・2～3 人</span>';$("chapter").textContent="線上共享生涯";$("title").textContent="建立或加入共享世界";$("text").textContent="進房後直接遊玩原本的完整生涯或精華生涯；訓練、事件、比賽、健康、升學、合約與退休規則完全沿用單人模式。";const existing=state.rooms.length?`<div class="kbExistingWorlds"><div class="specialKicker">繼續既有世界</div>${state.rooms.map(room=>`<button onclick="BasketballLifeKeyBattle.resume('${esc(room.code)}')"><b>${esc(room.code)}・${esc(room.team_name)}</b><small>${room.year?`${room.year}・${room.player_count} 人`: `等待開局・${room.player_count} 人`}</small></button>`).join("")}</div>`:"";$("special").innerHTML=`${existing}<div class="specialStage career"><div class="specialKicker">你的場上位置</div><b>${roles[state.role][0]}</b><br><span class="mut">${roles[state.role][1]}</span></div>`;$("choices").innerHTML=`<div class="twoChoices">${Object.entries(roles).map(([id,[name,detail]])=>`<button class="choice ${state.role===id?"is-selected":""}" onclick="BasketballLifeKeyBattle.selectRole('${id}')"><b>${name}</b><small>${detail}</small></button>`).join("")}</div><div class="twoChoices"><button class="choice ${state.mode==="complete"?"is-selected":""}" onclick="BasketballLifeKeyBattle.selectMode('complete')"><b>完整生涯</b><small>與單人完整模式完全相同，逐季遊玩所有流程。</small></button><button class="choice ${state.mode==="highlight"?"is-selected":""}" onclick="BasketballLifeKeyBattle.selectMode('highlight')"><b>精華生涯</b><small>與單人精華模式完全相同，保留重大章節與轉折。</small></button></div><div class="kbInlineJoin"><input id="kbRoomInput" maxlength="6" autocomplete="off" placeholder="輸入 6 碼世界代碼"><button class="btn" onclick="BasketballLifeKeyBattle.join()">加入世界</button><button class="next" onclick="BasketballLifeKeyBattle.create()">建立新世界</button></div><div class="kbError">${esc(state.error)}</div>`}
 function renderWaiting(data){lobbyHeader(data);$("titleShelf").innerHTML=`<span class="titleBadge">世界｜${esc(data.room.code)}</span><button class="titleBadge kbShelfButton" onclick="BasketballLifeKeyBattle.copyCode()">複製代碼</button><button class="titleBadge kbShelfButton" onclick="BasketballLifeKeyBattle.switchRoom()">切換世界</button>`;$("chapter").textContent=`共享世界｜${data.room.code}`;$("title").textContent="等待隊友建立球員";$("text").textContent=data.players.length<2?"至少再一名真人玩家加入後才能開始。":"人數已足夠；房主選擇完整或精華節奏後，所有人直接進入同一套正式生涯引擎。";$("special").innerHTML=peers(data);$("choices").innerHTML=`${data.can_start?`<button class="choice kbStartChoice" onclick="BasketballLifeKeyBattle.start()"><b>開始${state.mode==="highlight"?"精華":"完整"}生涯</b><small>不是簡化事件版；直接從原本 HBL 生涯開局。</small></button>`:""}<div class="kbError">${esc(state.error)}</div>`}
 function showSetupPanel(){stop();$("game")?.classList.add("hidden");$("communityPage")?.classList.add("hidden");$("onlineBattlePage")?.classList.add("hidden");$("setup")?.classList.remove("hidden");$("sharedWorldSetup")?.classList.remove("hidden")}
 function setupSummary(){const setup=currentSetup();return `${esc(setup.name)}・${setup.pos}・${setup.height} cm・臂展 ${setup.wingspan} cm・${esc(setup.birthplace==="RANDOM"?"隨機出生地":setup.birthplace)}・Seed ${esc(setup.seed||"尚未設定")}`}
 function renderLobby(){showSetupPanel();state.mode=chosenCareerMode==="highlight"?"highlight":"complete";const panel=$("sharedWorldSetup"),existing=state.rooms.length?`<div class="kbExistingWorlds"><div class="specialKicker">共享生涯存檔</div>${state.rooms.map(room=>{const saved=!!window.BasketballLifeCareerSave?.readShared?.(room.code);return `<div class="kbSaveSlot"><button class="kbSaveContinue" onclick="BasketballLifeKeyBattle.resume('${esc(room.code)}')"><b>${saved?"繼續生涯":"進入世界"}｜${esc(room.code)}・${esc(room.team_name)}</b><small>${room.year?`${room.year}・${room.player_count} 人`:`等待開局・${room.player_count} 人`}・${saved?"本機進度已保存":"此裝置尚無生涯存檔"}</small></button><button class="kbSaveCancel" onclick="BasketballLifeKeyBattle.cancelSharedSave('${esc(room.code)}')">取消這份生涯</button></div>`}).join("")}</div>`:"";panel.innerHTML=`<div class="setupSectionHead"><div><b>線上共享生涯</b><small>先選擇要繼續的共享存檔；只有點選後才會進入遊戲。</small></div><button class="btn" type="button" onclick="BasketballLifeKeyBattle.close()">取消</button></div><div class="bodyImpact"><b>建立新世界時使用</b><br>${setupSummary()}</div>${existing}<div class="kbInlineJoin"><input id="kbRoomInput" maxlength="6" autocomplete="off" placeholder="輸入 6 碼世界代碼"><button class="btn" onclick="BasketballLifeKeyBattle.join()">加入世界</button><button class="next" onclick="BasketballLifeKeyBattle.create()">建立新世界</button></div><div class="kbError">${esc(state.error)}</div>`;panel.scrollIntoView({block:"nearest"})}
 function renderWaiting(data){showSetupPanel();const panel=$("sharedWorldSetup");panel.innerHTML=`<div class="setupSectionHead"><div><b>共享世界｜${esc(data.room.code)}</b><small>${data.players.length<2?"等待至少一名真人玩家加入。":"球員設定完成；開始後直接進入上方選定的正式生涯。"}</small></div><button class="btn" type="button" onclick="BasketballLifeKeyBattle.copyCode()">複製代碼</button></div>${peers(data)}${data.can_start?`<button class="start" onclick="BasketballLifeKeyBattle.start()">開始${state.mode==="highlight"?"精華":"完整"}生涯</button>`:""}<div class="kbError">${esc(state.error)}</div>`}
 function sharedContext(data){const role=data.my_role||data.my_career?.position||state.role,setup=readSetup(data.room.code)||currentSetup();return {...setup,code:data.room.code,role,pos:setup.pos||roles[role]?.[2]||"PG",name:setup.name||data.my_career?.player_name||nickname()||"共享世界球員",mode:data.world.mode||setup.mode||"complete",seed:/^[A-Z0-9]{8}$/.test(setup.seed||"")?setup.seed:(data.world.seed||`${data.room.code}SW`)}}
 function launch(data){stop();state.room=data;const context=sharedContext(data);if(typeof p!=="undefined"&&p?.onlineSharedWorld?.code===context.code){showGame();if(p.onlineSharedWorld.pendingMidseasonResult)return midseasonResultScreen(p.onlineSharedWorld.pendingMidseasonResult.result,p.onlineSharedWorld.pendingMidseasonResult.year);if(p.onlineSharedWorld.pendingResult)return resultScreen(p.onlineSharedWorld.pendingResult.result,p.onlineSharedWorld.pendingResult.year);if(typeof window.render==="function")window.render();return}if(window.BasketballLifeCareerSave?.readShared?.(context.code)){window.BasketballLifeCareerSave.resumeShared(context.code);setTimeout(()=>{if(p?.onlineSharedWorld?.pendingMidseasonResult)midseasonResultScreen(p.onlineSharedWorld.pendingMidseasonResult.result,p.onlineSharedWorld.pendingMidseasonResult.year);else if(p?.onlineSharedWorld?.pendingResult)resultScreen(p.onlineSharedWorld.pendingResult.result,p.onlineSharedWorld.pendingResult.year)},0);return}startCareer(context)}
 function renderRoom(){if(!state.room)return renderLobby();if(state.room.world)return launch(state.room);renderWaiting(state.room)}
 async function request(path,options){if(state.busy)return null;state.busy=true;state.error="";try{return await window.BasketballLifeOnline.request(`online/key-battle/${path}`,options)}catch(error){state.error=error.message||"連線失敗";return null}finally{state.busy=false}}
 async function refresh(){if(!state.room)return;const data=await request(`rooms/${state.room.room.code}`);if(data){state.room=data;if(data.world)launch(data);else renderWaiting(data)}}
 function startPolling(){stop();state.poll=setInterval(refresh,1400)}
 async function loadRooms(){const data=await request("rooms"),hidden=hiddenRooms();state.rooms=(data?.rooms||[]).filter(room=>!hidden.has(room.code));return state.rooms}
 async function resume(code){const data=await request(`rooms/${code}`);if(data){state.room=data;remember(data.room.code);renderRoom();if(!data.world)startPolling()}else renderRoom()}
 async function open(){if(!nickname()){window.BasketballLifeOnline?.showNicknameModal?.();return}state.error="";state.room=null;await loadRooms();renderLobby()}
 function close(){stop();$("game")?.classList.add("hidden");$("sharedWorldSetup")?.classList.add("hidden");$("setup")?.classList.remove("hidden")}
 function selectRole(role){if(roles[role]){state.role=role;chosenPos=roles[role][2];if(typeof refreshSetupBody==="function")refreshSetupBody(true);renderLobby()}}
 function selectMode(mode){state.mode=mode==="highlight"?"highlight":"complete";chosenCareerMode=state.mode;state.room?renderWaiting(state.room):renderLobby()}
 function remember(code){try{localStorage.setItem("bl_key_battle_room",code)}catch(_){}}
 async function create(){const setup=currentSetup();if(!/^[A-Z0-9]{8}$/.test(setup.seed)){state.error="請先回首頁設定完整 8 碼 Seed";return renderLobby()}state.role=setupRole(setup.pos);const data=await request("rooms",{method:"POST",body:{role:state.role}});if(data){state.room=data;saveSetup(data.room.code);remember(data.room.code);renderRoom();startPolling()}else{await loadRooms();renderRoom()}}
 async function join(){const code=String($("kbRoomInput")?.value||"").trim().toUpperCase(),setup=currentSetup();if(!/^[A-Z2-9]{6}$/.test(code)){state.error="請輸入正確的 6 碼世界代碼";renderLobby();return}if(!/^[A-Z0-9]{8}$/.test(setup.seed)){state.error="請先回首頁設定完整 8 碼 Seed";return renderLobby()}state.role=setupRole(setup.pos);const data=await request(`rooms/${code}/join`,{method:"POST",body:{role:state.role}});if(data){setRoomHidden(code,false);state.room=data;saveSetup(data.room.code);remember(data.room.code);renderRoom();startPolling()}else renderLobby()}
 async function start(){if(!state.room)return;const data=await request(`rooms/${state.room.room.code}/start`,{method:"POST",body:{mode:state.mode}});if(data)launch(data);else renderWaiting(state.room)}
 async function copyCode(){const code=state.room?.room?.code;if(!code)return;try{await navigator.clipboard.writeText(code);state.error="共享世界代碼已複製"}catch(_){state.error=`共享世界代碼：${code}`}}
 async function switchRoom(){stop();state.room=null;state.error="";try{localStorage.removeItem("bl_key_battle_room")}catch(_){}await loadRooms();renderLobby()}
 function snapshot(ready=true){const season=[...(p.seasonHistory||[])].reverse().find(row=>Number(row.year)===Number(p.year))||(p.seasonHistory||[]).slice(-1)[0],playoff=(season?.tourneys||[]).find(row=>/季後賽/.test(String(row?.name||""))),playoffFinish=String(playoff?.finish||"");return {year:p.year,age:p.age,path:p.path,team:p.team,overall:typeof overall==="function"?overall():0,health:p.health,reputation:p.rep,stage:p.stage,mode:p.careerMode,retired:p.retired,ready,nationalEligible:!(p.nationalTeamBanUntil&&p.nationalTeamBanUntil>p.year),injured:!!(p.currentInjury||p.injury),fatigue:p.fatigue||0,careerSeason:p.careerSeason||p.seasonHistory?.length||0,playoffFinish,madePlayoffs:!!playoff&&!/未晉級/.test(playoffFinish)}}
 function waitingActions(){return `<div class="kbInlineJoin"><button class="btn" onclick="BasketballLifeKeyBattle.retrySeasonSync()">重新同步</button><button class="btn" onclick="BasketballLifeKeyBattle.backToSaveList()">返回多人存檔</button><button class="btn" onclick="BasketballLifeKeyBattle.leaveSharedCareer()">取消這份生涯</button></div>`}
 function waitingScreen(players=[]){if(typeof window.render==="function")window.render();$("chapter").textContent=`共享世界・${p.year}`;$("title").textContent="本季完成，等待隊友";$("text").textContent="你的進度已送出。所有真人玩家完成同一年球季後，會進入一個共同事件，再一起前往下一季。";$("special").innerHTML=`<div class="kbOnlinePeers">${players.map(row=>`<article class="kbCareerCard ${row.is_me?"mine":""}"><b>${esc(row.player_name)}${row.is_me?"（你）":""}</b><small>${esc(row.team_name)}・OVR ${row.overall??"—"}</small><em>${row.ready?"本季已完成":"仍在遊玩本季"}</em></article>`).join("")}</div><div class="kbError">${esc(state.error)}</div>${waitingActions()}`;$("choices").innerHTML="";$("next").classList.add("hidden")}
 function intersectionScreen(data){const event=data.intersection,midseason=event.checkpoint==="midseason",story=midseason?"季中共同回合・所有真人共同決定":event.storyLine?`跨季多人主線・第 ${event.storyNode}/3 節`:"真正共同事件",handler=midseason?"chooseMidseason":"chooseIntersection";$("chapter").textContent=`共享世界・${p.year}`;$("title").textContent=event.title;$("text").textContent=event.detail;$("special").innerHTML=`<div class="bodyImpact"><b>${story}</b><br>${midseason?"不同位置要互補、真人對手會互相克制；沒有人能單獨完成本回合。":"每個人都要用自己的球員作答；全員完成後才會形成共同結果。"}</div><div class="kbError">${esc(state.error)}</div>${waitingActions()}`;$("choices").innerHTML=data.submitted?`<div class="bodyImpact">你的選擇已送出，正在等待隊友。</div>`:event.options.map(option=>`<button class="choice" onclick="BasketballLifeKeyBattle.${handler}('${option.id}')"><b>${esc(option.label)}</b><small>${esc(option.detail)}</small></button>`).join("");$("next").classList.add("hidden")}
 function applyIntersection(result,year){if(!result)return;const applied=p.onlineSharedWorld.appliedIntersections||(p.onlineSharedWorld.appliedIntersections=[]),id=result.eventId||`shared-${year}`;if(applied.includes(id))return;const fx=result.effect||{};p.rep=Math.max(-40,Math.min(100,(p.rep||0)+(fx.rep||0)));p.health=Math.max(20,Math.min(100,(p.health||100)+(fx.health||0)));p.confidence=Math.max(0,Math.min(100,(p.confidence||50)+(fx.confidence||0)));p.fatigue=Math.max(0,Math.min(100,(p.fatigue||0)+(fx.fatigue||0)));p.onlineSharedWorld.history=(p.onlineSharedWorld.history||[]).concat([{year,eventId:id,type:result.eventType,storyLine:result.storyLine||null,storyNode:result.storyNode||0,label:result.label,title:result.shared?.title,detail:result.followUp?.detail,causedBy:result.causedBy||[],standings:result.shared?.standings||[],cooperation:Number(result.shared?.cooperationDelta)||0}]).slice(-40);applied.push(id);if(typeof logIt==="function")logIt(`${result.shared?.title||"共同事件完成"}：${result.label||"完成選擇"}`)}
 function applyNextSeasonIntersection(result,year){const id=result?.eventId||`shared-${year}`,applied=p.onlineSharedWorld.appliedNextSeasonIntersections||(p.onlineSharedWorld.appliedNextSeasonIntersections=[]);if(applied.includes(id))return;const risk=Number(result?.effect?.planRisk)||0;p.planRiskMod=(p.planRiskMod||0)+risk;applied.push(id)}
 function resultScreen(result,year){state.finishing=false;state.pendingAdvance={result,year};p.onlineSharedWorld.pendingResult={result,year};applyIntersection(result,year);saveCareerNow();const standings=result.shared?.standings||[],fx=result.effect||{},impact=[`外界評價 ${fx.rep>=0?"+":""}${fx.rep||0}`,`健康 ${fx.health>=0?"+":""}${fx.health||0}`,`信心 ${fx.confidence>=0?"+":""}${fx.confidence||0}`,`下季傷病風險 ${fx.planRisk>=0?"+":""}${fx.planRisk||0}`];$("chapter").textContent=`共享世界・${year} 共同結果`;$("title").textContent=result.shared?.title||"共同事件完成";$("text").textContent=result.shared?.detail||"所有玩家的選擇已共同形成結果。";$("special").innerHTML=`<div class="kbOnlinePeers">${standings.map((row,index)=>`<article class="kbCareerCard"><span>#${index+1}・${esc(row.label)}</span><b>${esc(row.player_name)}</b><small>${esc(row.team_name)}・共同表現 ${row.score}</small></article>`).join("")}</div><div class="bodyImpact"><b>你的實際後果</b><br>${impact.join("・")}<br>${(result.causedBy||[]).map(esc).join("<br>")||esc(result.followUp?.detail||"")}</div>${waitingActions()}`;$("choices").innerHTML=`<button class="choice" onclick="BasketballLifeKeyBattle.confirmSharedAdvance()"><b>確認結果，進入下一季</b><small>共同結果已寫入生涯；確認後才會執行原本的球季推進。</small></button>`;$("next").classList.add("hidden");restoreScrollFocus()}
 function confirmSharedAdvance(){const pending=state.pendingAdvance||p?.onlineSharedWorld?.pendingResult;if(!pending)return;const {year,result}=pending;p.onlineSharedWorld.readyYear=year;delete p.onlineSharedWorld.pendingResult;state.pendingAdvance=null;const finish=state.localFinish||window.finishSeasonLocal;state.localFinish=null;if(typeof finish==="function")finish();applyNextSeasonIntersection(result,year);saveCareerNow()}
 function midseasonComplete(year=p?.year){return (p?.onlineSharedWorld?.midseasonYears||[]).includes(Number(year))}
 function checkpointWaitingScreen(players=[]){if(typeof window.render==="function")window.render();$("chapter").textContent=`共享世界・${p.year}・季中` ;$("title").textContent="已到達共同回合，等待隊友";$("text").textContent="其他真人仍在完成本季前半段。全員到達後，會在這個原生生涯頁共同完成一個攻防或合作回合。";$("special").innerHTML=`<div class="kbOnlinePeers">${players.map(row=>`<article class="kbCareerCard ${row.is_me?"mine":""}"><b>${esc(row.player_name)}${row.is_me?"（你）":""}</b><small>${esc(row.team_name)}・OVR ${row.overall??"—"}</small><em>${row.ready?"已到達共同回合":"仍在遊玩前半季"}</em></article>`).join("")}</div><div class="kbError">${esc(state.error)}</div>${waitingActions()}`;$("choices").innerHTML="";$("next").classList.add("hidden")}
 async function syncMidseason(run=state.checkpointRun){if(!state.checkpointing||run!==state.checkpointRun)return;try{const data=await window.BasketballLifeOnline.request(`online/key-battle/rooms/${p.onlineSharedWorld.code}/checkpoint`,{method:"POST",body:snapshot(false)});if(run!==state.checkpointRun)return;if(data.advance){if(data.result&&Object.keys(data.result).length)return midseasonResultScreen(data.result,p.year);return completeMidseasonWithoutEvent()}state.error="";data.intersection?intersectionScreen(data):checkpointWaitingScreen(data.players);setTimeout(()=>syncMidseason(run),1400)}catch(error){if(run!==state.checkpointRun)return;state.error=error.message||"季中同步失敗";checkpointWaitingScreen([]);setTimeout(()=>syncMidseason(run),2500)}}
 function maybeMidseasonCheckpoint(resume=null,force=false){if(!p?.onlineSharedWorld||p.retired||midseasonComplete()||state.checkpointing)return false;const threshold=Math.max(1,Math.ceil(Number(p.seasonEventCount||2)/2)),due=force||(p.stage==="events"&&Number(p.eventIndex||0)>=threshold);if(!due)return false;state.checkpointing=true;state.checkpointResume=typeof resume==="function"?resume:null;state.checkpointRun++;syncMidseason(state.checkpointRun);return true}
 async function chooseMidseason(choice){if(!state.checkpointing)return;try{const data=await window.BasketballLifeOnline.request(`online/key-battle/rooms/${p.onlineSharedWorld.code}/checkpoint-choice`,{method:"POST",body:{year:p.year,choice}});if(data.advance)return midseasonResultScreen(data.result,p.year);intersectionScreen(data)}catch(error){state.error=error.message||"季中共同選擇送出失敗";state.checkpointRun++;syncMidseason(state.checkpointRun)}}
 function midseasonResultScreen(result,year){state.checkpointing=false;p.onlineSharedWorld.pendingMidseasonResult={result,year};applyIntersection(result,year);saveCareerNow();const standings=result.shared?.standings||[],fx=result.effect||{};$("chapter").textContent=`共享世界・${year}・季中結果`;$("title").textContent=result.shared?.title||"季中共同回合完成";$("text").textContent=result.shared?.detail||"所有真人的選擇已形成同一結果。";$("special").innerHTML=`<div class="kbOnlinePeers">${standings.map((row,index)=>`<article class="kbCareerCard"><span>#${index+1}・${esc(row.label)}</span><b>${esc(row.player_name)}</b><small>${esc(row.team_name)}・共同表現 ${row.score}</small></article>`).join("")}</div><div class="bodyImpact"><b>本季立即後果</b><br>外界評價 ${fx.rep>=0?"+":""}${fx.rep||0}・健康 ${fx.health>=0?"+":""}${fx.health||0}・信心 ${fx.confidence>=0?"+":""}${fx.confidence||0}・疲勞 +${fx.fatigue||0}<br>${(result.causedBy||[]).map(esc).join("<br>")}</div>${waitingActions()}`;$("choices").innerHTML=`<button class="choice" onclick="BasketballLifeKeyBattle.confirmMidseasonAdvance()"><b>確認共同結果，繼續本季</b><small>回到原本完整／精華生涯流程，保留所有已發生的個人事件。</small></button>`;$("next").classList.add("hidden");restoreScrollFocus()}
 function completeMidseasonWithoutEvent(){state.checkpointing=false;p.onlineSharedWorld.midseasonYears=[...new Set([...(p.onlineSharedWorld.midseasonYears||[]),Number(p.year)])];const resume=state.checkpointResume;state.checkpointResume=null;saveCareerNow();if(typeof resume==="function")return resume();if(p.stage==="events"&&typeof nextStep==="function")return nextStep();if(p.stage==="points"&&typeof finishSeason==="function")return finishSeason();if(typeof window.render==="function")window.render()}
 function confirmMidseasonAdvance(){const pending=p?.onlineSharedWorld?.pendingMidseasonResult;if(!pending)return;p.onlineSharedWorld.midseasonYears=[...new Set([...(p.onlineSharedWorld.midseasonYears||[]),Number(pending.year)])];p.planRiskMod=(p.planRiskMod||0)+Number(pending.result?.effect?.planRisk||0);delete p.onlineSharedWorld.pendingMidseasonResult;const resume=state.checkpointResume;state.checkpointResume=null;saveCareerNow();if(typeof resume==="function")return resume();if(p.stage==="events"&&typeof nextStep==="function")return nextStep();if(p.stage==="points"&&typeof finishSeason==="function")return finishSeason();if(typeof window.render==="function")window.render()}
 async function syncSeason(run=state.finishRun){if(!state.finishing||run!==state.finishRun)return;const year=p.year,code=p.onlineSharedWorld.code;try{const data=await window.BasketballLifeOnline.request(`online/key-battle/rooms/${code}/sync`,{method:"POST",body:snapshot(true)});if(run!==state.finishRun)return;if(data.advance){if(data.result&&Object.keys(data.result).length)return resultScreen(data.result,year);p.onlineSharedWorld.readyYear=year;const finish=state.localFinish;state.localFinish=null;state.finishing=false;if(typeof finish==="function")finish();return saveCareerNow()}state.error="";data.intersection?intersectionScreen(data):waitingScreen(data.players);setTimeout(()=>syncSeason(run),1400)}catch(error){if(run!==state.finishRun)return;state.error=error.message||"同步失敗";waitingScreen([]);setTimeout(()=>syncSeason(run),2500)}}
 async function finishSeason(localFinish){if(state.finishing)return;if(maybeMidseasonCheckpoint(()=>finishSeason(localFinish),true))return;state.finishing=true;state.localFinish=localFinish;state.finishRun++;await syncSeason(state.finishRun)}
 async function chooseIntersection(choice){if(!state.finishing)return;try{const data=await window.BasketballLifeOnline.request(`online/key-battle/rooms/${p.onlineSharedWorld.code}/intersection`,{method:"POST",body:{year:p.year,choice}});if(data.advance)return resultScreen(data.result,p.year);intersectionScreen(data)}catch(error){state.error=error.message||"共同事件送出失敗";retrySeasonSync()}}
 function retrySeasonSync(){if(!p?.onlineSharedWorld)return;state.error="";if(!state.finishing)state.finishing=true;state.finishRun++;syncSeason(state.finishRun)}
 async function backToSaveList(){state.finishing=false;state.finishRun++;state.localFinish=null;state.room=null;await loadRooms();renderLobby()}
 async function cancelSharedSave(code){if(!code||!confirm("確定取消這份共享生涯？此裝置的共享存檔會刪除並從清單隱藏，但不會刪除隊友資料；日後仍可輸入世界代碼重新加入。"))return;window.BasketballLifeCareerSave?.clearShared?.(code);setRoomHidden(code,true);try{if(localStorage.getItem("bl_key_battle_room")===code)localStorage.removeItem("bl_key_battle_room")}catch(_){}state.rooms=state.rooms.filter(room=>room.code!==code);renderLobby()}
 async function leaveSharedCareer(){const code=p?.onlineSharedWorld?.code;if(!code)return;state.finishing=false;state.finishRun++;state.localFinish=null;await cancelSharedSave(code)}
 async function notifyRetirement(){const code=p?.onlineSharedWorld?.code;if(!code)return;try{await window.BasketballLifeOnline.request(`online/key-battle/rooms/${code}/retire`,{method:"POST",body:{year:p.year}})}catch(error){console.warn("共享世界退休狀態稍後重試",error)}}
 window.BasketballLifeKeyBattle={open,close,selectRole,selectMode,create,join,start,copyCode,switchRoom,resume,finishSeason,maybeMidseasonCheckpoint,chooseMidseason,confirmMidseasonAdvance,chooseIntersection,confirmSharedAdvance,retrySeasonSync,backToSaveList,cancelSharedSave,leaveSharedCareer,notifyRetirement};
})();
